# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline

# Add permissions block at the top level
permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - PROD
      reason:
        description: "Reason for manual trigger"
        required: false
        type: string
  push:
    branches: [main]
    paths:
      - "app/**"
      - "kubernetes/applications/python-app/**"
      - "Dockerfile"
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "kubernetes/applications/python-app/**"
      - "Dockerfile"

env:
  DOCKER_IMAGE: ironcladgeek/platform-eng-python-app
  VERSION: 1.0.${{ github.run_number }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd app
          pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'DEV' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:v${{ env.VERSION }}
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Update Kubernetes manifests
        run: |
          cd kubernetes/applications/python-app
          sed -i "s|image: .*|image: ${{ env.DOCKER_IMAGE }}:v${{ env.VERSION }}|" deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add kubernetes/applications/python-app/deployment.yaml
          git commit -m "Update docker image to v${{ env.VERSION }}" || echo "No changes to commit"
          git push
